"use client";
import { AuthContextProvider } from "@/contexts/AuthContext";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useEffect } from "react";
import "./globals.css";
  import { ToastContainer } from "react-toastify";
  

  import "react-toastify/dist/ReactToastify.css";
import ProgressProvider from "@/components/ProgressProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	useEffect(() => {
		console.log("root layout");
		return () => {};
	}, []);

	return (
		<html lang="en" data-theme="light">
			<body className="font-sans">
				<AuthContextProvider>
						<ToastContainer
						position="bottom-center"
						autoClose={5000}
						hideProgressBar={false}
						newestOnTop={false}
						closeOnClick
						rtl={false}
						pauseOnFocusLoss
						draggable
						pauseOnHover
						theme="light"
					/>
					<ProgressProvider>
					{children}
					</ProgressProvider>
					
				</AuthContextProvider>
			</body>
		</html>
	);
}
