"use client";
import { AuthContextProvider } from "@/contexts/AuthContext";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useEffect } from "react";
import {  ModalProvider } from "@/contexts/ModalContext";
import Modal from "@/components/Modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	useEffect(() => {
		console.log("root layout");
		return () => {};
	}, []);

	return (
		<html lang="en" data-theme="light">
			<body className={inter.className}>
				<AuthContextProvider>
					<ModalProvider>
						<Modal />
						{children}
					</ModalProvider>
				</AuthContextProvider>
			</body>
		</html>
	);
}
