import { OrderStausEnum } from "./enums/orderStatusEnum";

export const preferences = [
	"Leafy",
	"Root",
	"Cruciferous",
	"Allium",
	"Legume",
	"Solanaceous",
	"Gourd",
	"Cucumber",
	"Miscellaneous",
];

export const healthConditionArr = [
	"Heart Health",
	"Bone Health",
	"Eye Health",
	"Anti-Inflammatory",
	"Digestive Health",
	"Immune Support",
	"Antioxidant Support",
	"Blood Pressure",
	"Weight Management",
	"Diabetes Management",
];

export const NepalDistrict = [
	"Achham",
	"Arghakhanchi",
	"Baglung",
	"Baitadi",
	"Bajhang",
	"Bajura",
	"Banke",
	"Bara",
	"Bardiya",
	"Bhaktapur",
	"Bhojpur",
	"Chitwan",
	"Dadeldhura",
	"Dailekh",
	"Dang",
	"Darchula",
	"Dhading",
	"Dhankuta",
	"Dhanusa",
	"Dolakha",
	"Dolpa",
	"Doti",
	"Gorkha",
	"Gulmi",
	"Humla",
	"Ilam",
	"Jajarkot",
	"Jhapa",
	"Jumla",
	"Kailali",
	"Kalikot",
	"Kanchanpur",
	"Kapilvastu",
	"Kaski",
	"Kathmandu",
	"Kavrepalanchok",
	"Khotang",
	"Lalitpur",
	"Lamjung",
	"Mahottari",
	"Makwanpur",
	"Manang",
	"Morang",
	"Mugu",
	"Mustang",
	"Myagdi",
	"Nawalparasi",
	"Nuwakot",
	"Okhaldhunga",
	"Palpa",
	"Panchthar",
	"Parbat",
	"Parsa",
	"Pyuthan",
	"Ramechhap",
	"Rasuwa",
	"Rautahat",
	"Rolpa",
	"Rukum",
	"Rupandehi",
	"Salyan",
	"Sankhuwasabha",
	"Saptari",
	"Sarlahi",
	"Sindhuli",
	"Sindhupalchok",
	"Siraha",
	"Solukhumbu",
	"Sunsari",
	"Surkhet",
	"Syangja",
	"Tanahu",
	"Taplejung",
	"Terhathum",
	"Udayapur",
];

export const orderData = [
	{
		id: 1,
		createdAt: new Date(),
		updatedAt: new Date(),
		orderNumber: "orderNumber00012",
		status: OrderStausEnum.PLACED,
		total: 1200.0,
		orderBy: {
			id: 1,
			email: "chirag777@g.com",
			name: "chirag",
		},
		userSubscription: {
			id: 1,
			subscribed: {
				id: 1,
				name: "subscription A",
			},
		},
		orderDetails: [
			{
				id: 1,
				createdAt: new Date(),
				updatedAt: new Date(),
				quantity: 2,
				price: 50,
				total: 100,
				product: {
					id: 1,
					createdAt: new Date(),
					updatedAt: new Date(),
					name: "orange",
					image: {
						url: "https://cdn.pixabay.com/photo/2016/08/11/08/04/vegetables-1584999_1280.jpg",
					},
				},
			},
			{
				id: 2,
				createdAt: new Date(),
				updatedAt: new Date(),
				quantity: 2,
				price: 50,
				total: 100,
				product: {
					id: 1,
					createdAt: new Date(),
					updatedAt: new Date(),
					name: "apple",
					image: {
						url: "https://cdn.pixabay.com/photo/2016/08/11/08/04/vegetables-1584999_1280.jpg",
					},
				},
			},
		],
	},
	{
		id: 3,
		createdAt: new Date(),
		updatedAt: new Date(),
		orderNumber: "orderNumber00012",
		status: OrderStausEnum.PLACED,
		total: 1200.0,
		orderBy: {
			id: 1,
			email: "chirag777@g.com",
			name: "chirag",
		},
		userSubscription: {
			id: 1,
			subscribed: {
				id: 1,
				name: "subscription A",
			},
		},
		orderDetails: [
			{
				id: 1,
				createdAt: new Date(),
				updatedAt: new Date(),
				quantity: 2,
				price: 50,
				total: 100,
				product: {
					id: 1,
					createdAt: new Date(),
					updatedAt: new Date(),
					name: "orange",
					image: {
						url: "https://cdn.pixabay.com/photo/2016/08/11/08/04/vegetables-1584999_1280.jpg",
					},
				},
			},
			{
				id: 2,
				createdAt: new Date(),
				updatedAt: new Date(),
				quantity: 2,
				price: 50,
				total: 100,
				product: {
					id: 1,
					createdAt: new Date(),
					updatedAt: new Date(),
					name: "apple",
					image: {
						url: "https://cdn.pixabay.com/photo/2016/08/11/08/04/vegetables-1584999_1280.jpg",
					},
				},
			},
		],
	},
	{
		id: 2,
		createdAt: new Date(),
		updatedAt: new Date(),
		orderNumber: "orderNumber00012",
		status: OrderStausEnum.PLACED,
		total: 1200.0,
		orderBy: {
			id: 1,
			email: "chirag777@g.com",
			name: "chirag",
		},
		userSubscription: {
			id: 1,
			subscribed: {
				id: 1,
				name: "subscription A",
			},
		},
		orderDetails: [
			{
				id: 1,
				createdAt: new Date(),
				updatedAt: new Date(),
				quantity: 2,
				price: 50,
				total: 100,
				product: {
					id: 1,
					createdAt: new Date(),
					updatedAt: new Date(),
					name: "orange",
					image: {
						url: "https://cdn.pixabay.com/photo/2016/08/11/08/04/vegetables-1584999_1280.jpg",
					},
				},
			},
			{
				id: 2,
				createdAt: new Date(),
				updatedAt: new Date(),
				quantity: 2,
				price: 50,
				total: 100,
				product: {
					id: 1,
					createdAt: new Date(),
					updatedAt: new Date(),
					name: "apple",
					image: {
						url: "https://cdn.pixabay.com/photo/2016/08/11/08/04/vegetables-1584999_1280.jpg",
					},
				},
			},
		],
	},
];
