"use client";
import type { Metadata } from "next";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Router } from "next/router";
import { useEffect } from "react";
import { MdOutlineHome, MdOutlineMenu, MdOutlinePersonOutline, MdOutlineShoppingBag, MdSearch } from "react-icons/md";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const path: string = usePathname();
	useEffect(() => {
		return () => {};
	}, []);

	return (
		<div className="bg-base-200 min-h-screen">
			<nav className="flex w-full justify-between items-center p-2 sticky top-0 bg-base-200 z-50">
				<Link href={"/public/account"}>
					<MdOutlineMenu className="text-2xl text-primary" />
				</Link>
				<Link href="/public" className="text-xl font-bold text-primary">
					FreshBasket.
				</Link>
				<Link href={"/public/delivery"}>
					<MdOutlineShoppingBag className="text-2xl text-primary" />
				</Link>
			</nav>
			{children}
			<div className="btm-nav bg-base-100">
				<Link
					href={"/public"}
					className={`text-gray-500 ${
						path === "/public" &&
						"text-primary border-t-2 border-primary"
					}`}
				>
					<MdOutlineHome className="text-2xl" />
					<span className="btm-nav-label">Home</span>
				</Link>
				<Link
					href={"/public/delivery"}
					className={`text-gray-500 ${
						path === "/public/delivery" &&
						"text-primary border-t-2 border-primary"
					}`}
				>
					<MdOutlineShoppingBag className="text-2xl" />
					<span className="btm-nav-label">Orders</span>
				</Link>
				<Link
					href={"/public/account"}
					className={`text-gray-500 ${
						path === "/public/account" &&
						"text-primary border-t-2 border-primary"
					}`}
				>
					<MdOutlinePersonOutline className="text-2xl" />
					<span className="btm-nav-label">Account</span>
				</Link>
			</div>
		</div>
	);
}
